version: "3.5"

services:
  identifiertranslatorservice_authdb:
    image: openbookpublishers/tokens_db
    container_name: "identifiertranslatorservice_authdb"
    restart: unless-stopped
    volumes:
      - authdb:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - authdb.env

  identifiertranslatorservice_db:
    image: openbookpublishers/identifiers_db
    container_name: "identifiertranslatorservice_db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - db.env

  identifiertranslatorservice_api:
    build: ./
    container_name: "identifiertranslatorservice_api"
    restart: unless-stopped
    ports:
      - 8181:8080
    environment:
      - IDENTIFIERSDB_HOST=identifiertranslatorservice_db
      - AUTHDB_HOST=identifiertranslatorservice_authdb
    env_file:
      - api.env
      - db.env
      - authdb.env
    depends_on:
      - identifiertranslatorservice_authdb
      - identifiertranslatorservice_db

volumes:
  db:
  authdb:
