version: "3.5"

services:
  identifiertranslatorservice_db:
    image: openbookpublishers/identifiers_db
    container_name: "identifiertranslatorservice_db"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./config/db.env

  identifiertranslatorservice_api:
    image: openbookpublishers/identifier_translation_service
    container_name: "identifiertranslatorservice_api"
    restart: unless-stopped
    ports:
      - 8181:8080
    environment:
      - IDENTIFIERSDB_HOST=identifiertranslatorservice_db
    env_file:
      - ./config/api.env
      - ./config/db.env
    depends_on:
      - identifiertranslatorservice_db

volumes:
  db:
